{% set name = "python-twitter" %}
{% set version = "3.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77ebcf2344b622d2fa1e54a851971e030ae313c754863b435e5c1827be97a721

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - future
    - requests
    - requests-oauthlib
    - pytest-runner
  run:
    - python
    - future
    - requests
    - requests-oauthlib

test:
  imports:
    - twitter
  requires:
    - pytest
    - pytest-runner

about:
  home: https://github.com/bear/python-twitter
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: A Python wrapper around the Twitter API
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
